Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimplexSolver.Models;

namespace SimplexSolver.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(Simplex simplex)
        {
            TempData["Variaveis"] = simplex.Variaveis;
            TempData["Restricoes"] = simplex.Restricoes;
            TempData["Minimizar"] = simplex.Minimizar;
            TempData["ExibirPassoAPasso"] = simplex.ExibirPassoAPasso;
            return View(simplex);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SimplexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimplexSolver.Models;

namespace SimplexSolver.Controllers
{
    public class SimplexController : Controller
    {
        #region "Variáveis"
        QuadroSimplex quadroSimplex;
        int numeroVariaveis;
        int numeroRestricoes;
        int qtdColunas;
        int qtdInterations;
        decimal[] funcaoObjetiva;
        decimal[,] matrizNumerica;
        QuadroSimplex quadroSimplexOriginal;
        string[] Var;
        string[] ElementosOriginais;
        List<QuadroSimplex> Resultado;
        bool ExibirPassoAPasso;
        bool Minimizar;
        List<Result> Results;
        #endregion

        public IActionResult Index(Simplex simplex)
        {
            simplex.Variaveis = Convert.ToInt32(TempData["Variaveis"]);
            simplex.Restricoes = Convert.ToInt32(TempData["Restricoes"]);
            simplex.Minimizar = Convert.ToBoolean(TempData["Minimizar"]);
            ExibirPassoAPasso = Convert.ToBoolean(TempData["ExibirPassoAPasso"]);
            Minimizar = simplex.Minimizar;
            PrepareToExecute(simplex);
            if (!PreValidateFields(matrizNumerica, simplex.Minimizar))
                RedirectToAction("Index", "Home");
            Run();
            AnaliseSensibilidade();
            ViewData["ExibirPassoAPasso"] = ExibirPassoAPasso;
            return View(Resultado);
        }

        public void PrepareToExecute(Simplex simplex)
        {
            #region Preechimento das variáveis necessárias
            numeroVariaveis = simplex.Variaveis.Value;
            numeroRestricoes = simplex.Restricoes.Value;
            qtdColunas = (numeroVariaveis + numeroRestricoes) + 1;
            funcaoObjetiva = new decimal[qtdColunas];
            matrizNumerica = new decimal[numeroRestricoes, qtdColunas];
            Var = new string[numeroRestricoes + qtdColunas];
            #endregion

            #region Montar vetor da função objetivo
            for (int i = 0; i < qtdColunas; i++)
            {
                if (i < numeroVariaveis)
                    funcaoObjetiva[i] = (simplex.Minimizar ? simplex.objectiveVector[i] : -simplex.objectiveVector[i]);
                else
                    funcaoObjetiva[i] = 0;
            }
            #endregion

            #region Montar matriz de acordo com valores preenchidos
            for (int i = 0, k = 0; i < numeroRestricoes; i++)
            {
                for (int j = 0; j < numeroVariaveis + 1; j++)
                {
                    if (j == numeroVariaveis)
                        j = (numeroVariaveis + numeroRestricoes);
                    matrizNumerica[i, j] = simplex.Matriz[k];
                    k++;
                }
            }

            for (int i = 0; i < numeroRestricoes; i++)
            {
                matrizNumerica[i, numeroVariaveis + i] = 1;
            }
            #endregion

            #region Montar vetor com Elementos da operação
            for (int i = 0, j = 1, k = 1; i < (numeroRestricoes + qtdColunas); i++)
            {
                if (j > numeroRestricoes)
                {
                    j = 1;
                }
                if (i < numeroRestricoes)
                {
                    Var[i] = "F" + j;
                    j++;
                }
                else if (i < qtdColunas - 1)
                {
                    Var[i] = "X" + k;
                    k++;
                }
                else if (i < (numeroRestricoes + qtdColunas - 1))
                {
                    Var[i] = "F" + j;
                    j++;
                }
                else
                    Var[i] = "B";
            }
            #endregion

            ElementosOriginais = (string[])Var.Clone();

            quadroSimplex = new QuadroSimplex(Var, matrizNumerica, funcaoObjetiva);
            quadroSimplexOriginal = quadroSimplex.Clone(quadroSimplex);
        }

        public void Run()
        {
            //Inicialização da variável utilizada para exibição do resultado / passo a passo
            Resultado = new List<QuadroSimplex>();
            Results = new List<Result>();

            //Caso de exibição do passo a passo, inserir resultado antes da primeira interação
            if (ExibirPassoAPasso)
            {
                QuadroSimplex inicial = quadroSimplex.Clone(quadroSimplex);
                Resultado.Add(inicial);
            }

            while (quadroSimplex.FuncaoObjetiva.Where(x => x < 0).Any() && qtdInterations < 100)
            {
                #region Variaveis auxiliares
                qtdInterations++;
                decimal lowestValueToOut = 0;
                int positionOutLine = 0;
                int positionEnteringElement;
                #endregion


                //Buscando coluna do elemento que entrará na base
                positionEnteringElement = FindPositionLowestValue(quadroSimplex.FuncaoObjetiva);
                if (!(positionEnteringElement >= 0))
                    throw new Exception("Algo deu errado na busca da posicao");

                //Buscando linha do elemento que sairá da base
                for (int i = 0; i < quadroSimplex.Matriz.GetLength(0); i++)
                {
                    if (quadroSimplex.Matriz[i, positionEnteringElement] != 0)
                    {
                        decimal resultAux = quadroSimplex.Matriz[i, quadroSimplex.Matriz.GetLength(1) - 1] / quadroSimplex.Matriz[i, positionEnteringElement];
                        if ((resultAux < lowestValueToOut && resultAux >= 0) || lowestValueToOut == 0 && resultAux >= 0)
                        {
                            lowestValueToOut = resultAux;
                            positionOutLine = i;
                        }
                    }
                    else
                        continue;
                }

                //Cálculos das novas linhas/colunas
                if (!(quadroSimplex.Matriz[positionOutLine, positionEnteringElement] == 0))
                {
                    decimal pivo = quadroSimplex.Matriz[positionOutLine, positionEnteringElement];

                    for (int i = 0; i < quadroSimplex.Matriz.GetLength(1); i++)
                    {
                        quadroSimplex.Matriz[positionOutLine, i] = Convert.ToDecimal(quadroSimplex.Matriz[positionOutLine, i] / pivo);
                    }

                    for (int i = 0; i < quadroSimplex.Matriz.GetLength(0); i++)
                        if (i == positionOutLine)
                            continue;
                        else
                        {
                            decimal valoraux = -quadroSimplex.Matriz[i, positionEnteringElement];
                            for (int j = 0; j < quadroSimplex.Matriz.GetLength(1); j++)
                            {
                                quadroSimplex.Matriz[i, j] = (quadroSimplex.Matriz[positionOutLine, j] * valoraux) + quadroSimplex.Matriz[i, j];
                            }
                        }
                }

                #region Alocação do elemento para a posição correta no vetor de acordo com a entrada/saída de elementos
                var Element = quadroSimplex.Elementos[quadroSimplex.Matriz.GetLength(0) + positionEnteringElement];
                quadroSimplex.Elementos[quadroSimplex.Matriz.GetLength(0) + positionEnteringElement] = quadroSimplex.Elementos[positionOutLine];
                quadroSimplex.Elementos[positionOutLine] = Element;
                #endregion

                decimal valueLoadLine = -quadroSimplex.FuncaoObjetiva[positionEnteringElement];

                for (int i = 0; i < quadroSimplex.Matriz.GetLength(1); i++)
                    quadroSimplex.FuncaoObjetiva[i] = quadroSimplex.Matriz[positionOutLine, i] * valueLoadLine + quadroSimplex.FuncaoObjetiva[i];

                if (ExibirPassoAPasso)
                {
                    QuadroSimplex aux = quadroSimplex.Clone(quadroSimplex);
                    for (int i = numeroRestricoes; i < (numeroRestricoes + qtdColunas); i++)
                    {
                        aux.Elementos[i] = ElementosOriginais[i];
                    }
                    Resultado.Add(aux);
                }
            }

            if (!ExibirPassoAPasso)
            {
                QuadroSimplex final = quadroSimplex.Clone(quadroSimplex);
                for (int i = numeroRestricoes; i < (numeroRestricoes + qtdColunas); i++)
                {
                    final.Elementos[i] = ElementosOriginais[i];
                }
                Resultado.Add(final);
            }

            for (int i = 0; i < numeroRestricoes + qtdColunas; i++)
            {
                if (Results.Where(x => x.Elemento.Equals(quadroSimplex.Elementos[i])).Any())
                    continue;
                else
                    Results.Add(new Result()
                    {
                        Elemento = quadroSimplex.Elementos[i],
                        Valor = i < numeroRestricoes ? quadroSimplex.Matriz[i, qtdColunas - 1] :
                        (i == numeroRestricoes + qtdColunas - 1 ? (Minimizar ? -quadroSimplex.FuncaoObjetiva[qtdColunas - 1] : quadroSimplex.FuncaoObjetiva[qtdColunas - 1]) : 0)
                    });
            }

            ViewData["Resultado"] = Results;
        }

        public void AnaliseSensibilidade()
        {
            string[] ResultadoAnaliseSensibilidade = new string[(numeroRestricoes + numeroVariaveis + 1) * 14];
            int aumentarParametro = 0;
            int reduzirParametro = 0;

Views/Home/Index.cshtml
@model Simplex
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <br>
        <h1 class="display-4"><strong>Simplex</strong></h1>
        <br>
        <br>
    </div>

<fieldset>
    <form asp-controller="Home" asp-action="Index">
        <div class="row">
            <div class="col-sm-6">
                <input class="form-control" placeholder="Quantidade de Variáveis" asp-for="Variaveis" />
            </div>
            <div class="col-sm-6">
                <input class="form-control" placeholder="Quantidade de Restrições" asp-for="Restricoes" />
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-6">
                <label class="col-form-label">Escolha a operação</label>
                <select asp-for="Minimizar" class="custom-select">
                    <option value="false">Maximizar</option>
                    <option value="true">Minimizar</option>
                </select>
            </div>
            <div class="col-sm-6">
                <label class="col-form-label">Exibir passo a passo</label>
                <select asp-for="ExibirPassoAPasso" class="custom-select">
                    <option value="true">Sim</option>
                    <option value="false">Não</option>
                </select>
            </div>
        </div>
        <br>
        <button class="btn btn-sm btn-secondary" type="submit">Gravar</button>
    </form>
</fieldset>
<hr>
<fieldset>
    <legend>FORMULÁRIO</legend>
    <div id="form">
        @{
            if (Model.Restricoes == null)
                Model.Restricoes = 0;
            if (Model.Variaveis == null)
                Model.Variaveis = 0;

            Model.Matriz = new decimal[Model.Restricoes.Value * ((Model.Variaveis.Value * 2) + 1)];

                <form asp-controller="Simplex" asp-action="Index">
                    @if (Model.Variaveis > 0)
                    {
                        <fieldset>
                            <legend>Função Objetivo</legend>
                            <div class='row'>
                                @for (int j = 0; j < @Model.Variaveis; j++)
                                {
                                    if (j == @Model.Variaveis - 1)
                                    {
                                        <div class='col-sm-2'>
                                            <input asp-for="objectiveVector[j]" class='form-control'>
                                        </div>
                                    }
                                    else
                                    {

                                        <div class='col-sm-2'>
                                            <input asp-for="objectiveVector[j]" class='form-control'>
                                        </div>
                                        <p> + </p>
                                    }
                                }
                            </div>
                        </fieldset>
                        <br>
                        <hr>
                        <br>
                    }

                    @for (int i = 0, k = 0; i < @Model.Restricoes; i++)
                    {

                        <fieldset>
                            <legend>Restrição @(i + 1)</legend><div class='row'>
                                @for (int j = 0; j <= @Model.Variaveis; j++)
                                {

                                    if (j == @Model.Variaveis - 1)
                                    {
                                        <div class='col-sm-2'>
                                            <input asp-for="Matriz[k]" class='form-control'>
                                        </div>
                                        <p> &lt;= </p>
                                    }
                                    else if (j == @Model.Variaveis)
                                    {
                                        <div class='col-sm-2'>
                                            <input asp-for="Matriz[k]" class='form-control'>
                                        </div>
                                    }
                                    else
                                    {

                                        <div class='col-sm-2'>
                                            <input asp-for="Matriz[k]" class='form-control'>
                                        </div>
                                        <p> + </p>
                                    }
                                    k++;
                                }
                            </div>
                        </fieldset>
                        <hr>

                    }
                    <br><br>
                    <button class="btn btn-sm btn-secondary" type="submit">Executar Simplex</button>
                </form>
        }

    </div>
    <br>
</fieldset>
<hr>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript">
    //function gerarForm(argument) {
    //    let total_var = $('#qtde_var').val();
    //    let total_restricao = $('#qtde_restricoes').val();
    //    var $form = "<form action='/Simplex/Index' method='post'>";
    //    $form += "<hr>";
    //    for (var i = 0; i < total_restricao; i++)
    //    {
    //        $form += "<fieldset><legend>Restrição " + (i+1) + "</legend><div class='row'>"
    //        for (var j = 0; j <= total_var; j++)
    //        {
    //            if(j == total_var-1)
    //            {
    //                $form += "<div class='col-sm-2'><input id='var" + j + "_restricao" + i + "' type='text' asp-for='matriz[i,j] class='form-control'></div><p> = </p>"
    //            }
    //            else if (j == total_var)
    //            {
    //            $form += "<div class='col-sm-2'><input id='var" + j + "_restricao" + i + "' type='text' asp-for='matriz[i,j] class='form-control'></div>"
    //            }
    //            else
    //            {
    //            $form += "<div class='col-sm-2'><input id='var" + j + "_restricao" + i + "' type='text' asp-for='matriz[i,j] class='form-control'></div><p> + </p>"
    //            }
    //        }
    //        $form += "</div></fieldset>"
    //    }
    //    $form += "<a class='btn btn-sm btn-secondary' type='submit' >Executar</a>"
    //    $form += "</form>"

    //    $('#form').html($form);
    //}
</script>

Views/Home/_PartialView.cshtml

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@